- name: Update packages on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Update packages on Deiban based systems
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
